"""Active Graph Runtime. Public API surface.

The graph is the world. Behaviors are physics. The trace is the proof.
"""

from activegraph.behaviors.base import Behavior, LLMBehavior, RelationBehavior
from activegraph.behaviors.decorators import (
    behavior,
    clear_registry,
    get_registry,
    llm_behavior,
    register,
    relation_behavior,
)
from activegraph.core.clock import Clock, FrozenClock, TickingClock
from activegraph.core.event import Event
from activegraph.core.graph import Graph, Object, Relation
from activegraph.core.ids import IDGen
from activegraph.core.patch import Patch
from activegraph.core.view import View
from activegraph.errors import (
    ActiveGraphError,
    ConfigurationError,
    ExecutionError,
    MissingOptionalDependency,
    PackError,
    PatternError,
    RegistrationError,
    ReplayError,
    StorageError,
)
from activegraph.runtime.registration_errors import (
    AmbiguousBehaviorError,
    AmbiguousToolError,
    BehaviorNotFoundError,
    InvalidToolRegistration,
    ToolNotFoundError,
)
from activegraph.runtime.scheduler import InvalidActivateAfter
from activegraph.frame import Frame
from activegraph.llm.errors import LLMBehaviorError, MissingProviderError
from activegraph.policy import Policy
from activegraph.runtime.authority import AuthorityDecision
from activegraph.runtime.budget import Budget
from activegraph.runtime.diff import Diff, DivergentObject, DivergentRelation
from activegraph.runtime.dev_override import DevOverride
from activegraph.runtime.promote import (
    PromoteConflict,
    PromotePlan,
    PromoteResult,
)
from activegraph.runtime.config_errors import (
    IncompatibleRuntimeState,
    InvalidArgumentType,
    InvalidRuntimeConfiguration,
    RuntimeClosedError,
)
from activegraph.runtime.errors import ReplayDivergenceError
from activegraph.runtime.exec_errors import (
    ApplyPatchNotFoundError,
    ApprovalNotFoundError,
    InternalEvaluatorError,
    InvalidPatchLifecycleState,
    InvalidPatchOperationError,
    ObjectNotFoundError,
    PatchNotFoundError,
    PromoteConflictError,
    PromoteLineageError,
    RejectPatchNotFoundError,
    ReservedFieldError,
    RuntimeContextRequiredError,
)
from activegraph.runtime.patterns import UnsupportedPatternError
from activegraph.runtime.runtime import BehaviorFailure, RunQuantumResult, Runtime
from activegraph.sinks import (
    DeliveryContext,
    DeliveryMode,
    EventSink,
    JSONLEventSink,
    OverflowPolicy,
    RecordedDelivery,
    RecordingSink,
    SinkConfig,
    SinkHandle,
    SinkState,
    SinkStatus,
)
from activegraph.store import (
    BackendRegistration,
    CorruptMigrationEvent,
    CorruptedEventPayloadError,
    DuplicateEventError,
    EventNotFoundError,
    EventStore,
    FalkorDBGraphStore,
    GraphStore,
    InMemoryEventStore,
    InMemoryGraphStore,
    InvalidStoreURL,
    MigrationBackend,
    MigrationBackendCloseError,
    MigrationBackendConflictError,
    MigrationBackendLoadError,
    MigrationBackendProvider,
    MigrationCapability,
    MigrationItem,
    MigrationReport,
    MigrationRunReport,
    NonSerializableEventError,
    RunRecord,
    SQLiteEventStore,
    SchemaVersionMismatch,
    UnsupportedMigrationBackendError,
    UnsupportedMigrationCapabilityError,
    clear_migration_backend_cache,
    migrate,
    open_store,
    parse_store_url,
    register_migration_backend,
    resolve_migration_backend,
)
# v0.7 public surface for tools
from activegraph.tools import (
    MissingToolError,
    Tool,
    ToolContext,
    ToolError,
    UnknownToolError,
    clear_tool_registry,
    get_tool_registry,
    tool,
)
# v0.8 observability surface
from activegraph.observability import (
    Metrics,
    NoOpMetrics,
    OpenTelemetryMetrics,
    PrometheusMetrics,
    RuntimeStatus,
    configure_logging,
)
# v0.9 packs surface (top-level: the API for *using* packs from user code).
# Pack-aware decorators live under `activegraph.packs` and are intentionally
# NOT re-exported here — pack authors must import them from `activegraph.packs`
# so the import path makes the boundary explicit. CONTRACT v0.9 #3.
from activegraph.packs import (
    DiscoveredPack,
    EmptySettings,
    ObjectType,
    Pack,
    PackConflictError,
    PackError,
    PackNotFoundError,
    PackPolicy,
    PackPrompt,
    PackPromptLoadError,
    PackSchemaViolation,
    PackSettingsMissingError,
    PackValidationError,
    PackVersionConflictError,
    PendingApproval,
    RelationType,
    clear_discovery_cache,
    discover,
    load_by_name,
    load_prompts_from_dir,
)

__all__ = [
    "ActiveGraphError",
    "AmbiguousBehaviorError",
    "AmbiguousToolError",
    "ApplyPatchNotFoundError",
    "ApprovalNotFoundError",
    "AuthorityDecision",
    "Behavior",
    "BackendRegistration",
    "BehaviorFailure",
    "BehaviorNotFoundError",
    "Budget",
    "Clock",
    "ConfigurationError",
    "CorruptedEventPayloadError",
    "CorruptMigrationEvent",
    "Diff",
    "DeliveryContext",
    "DeliveryMode",
    "DevOverride",
    "DiscoveredPack",
    "DivergentObject",
    "DivergentRelation",
    "DuplicateEventError",
    "EmptySettings",
    "Event",
    "EventSink",
    "EventNotFoundError",
    "EventStore",
    "ExecutionError",
    "FalkorDBGraphStore",
    "Frame",
    "FrozenClock",
    "Graph",
    "GraphStore",
    "IDGen",
    "InMemoryEventStore",
    "InMemoryGraphStore",
    "IncompatibleRuntimeState",
    "InternalEvaluatorError",
    "InvalidActivateAfter",
    "InvalidArgumentType",
    "InvalidPatchLifecycleState",
    "InvalidPatchOperationError",
    "InvalidRuntimeConfiguration",
    "InvalidStoreURL",
    "InvalidToolRegistration",
    "JSONLEventSink",
    "LLMBehavior",
    "LLMBehaviorError",
    "Metrics",
    "MigrationBackend",
    "MigrationBackendCloseError",
    "MigrationBackendConflictError",
    "MigrationBackendLoadError",
    "MigrationBackendProvider",
    "MigrationCapability",
    "MigrationItem",
    "MigrationReport",
    "MigrationRunReport",
    "MissingOptionalDependency",
    "MissingProviderError",
    "MissingToolError",
    "NoOpMetrics",
    "NonSerializableEventError",
    "Object",
    "ObjectNotFoundError",
    "OpenTelemetryMetrics",
    "ObjectType",
    "OverflowPolicy",
    "Pack",
    "PackConflictError",
    "PackError",
    "PackNotFoundError",
    "PackPolicy",
    "PackPromptLoadError",
    "PackPrompt",
    "PackSchemaViolation",
    "PackSettingsMissingError",
    "PackValidationError",
    "PackVersionConflictError",
    "PatternError",
    "Patch",
    "PatchNotFoundError",
    "PendingApproval",
    "Policy",
    "PrometheusMetrics",
    "PromoteConflict",
    "PromoteConflictError",
    "PromoteLineageError",
    "PromotePlan",
    "PromoteResult",
    "RecordedDelivery",
    "RecordingSink",
    "Relation",
    "RelationBehavior",
    "RegistrationError",
    "RelationType",
    "ReplayDivergenceError",
    "ReplayError",
    "RejectPatchNotFoundError",
    "ReservedFieldError",
    "RunRecord",
    "Runtime",
    "RuntimeClosedError",
    "RunQuantumResult",
    "RuntimeContextRequiredError",
    "RuntimeStatus",
    "SQLiteEventStore",
    "SchemaVersionMismatch",
    "SinkConfig",
    "SinkHandle",
    "SinkState",
    "SinkStatus",
    "StorageError",
    "TickingClock",
    "Tool",
    "ToolContext",
    "ToolError",
    "ToolNotFoundError",
    "UnknownToolError",
    "UnsupportedPatternError",
    "UnsupportedMigrationBackendError",
    "UnsupportedMigrationCapabilityError",
    "View",
    "behavior",
    "clear_discovery_cache",
    "clear_migration_backend_cache",
    "clear_registry",
    "clear_tool_registry",
    "configure_logging",
    "discover",
    "get_registry",
    "get_tool_registry",
    "llm_behavior",
    "load_by_name",
    "load_prompts_from_dir",
    "migrate",
    "open_store",
    "parse_store_url",
    "register",
    "register_migration_backend",
    "relation_behavior",
    "resolve_migration_backend",
    "tool",
]

__version__ = "1.10.0"
